const ITEMS = [
    [ 1, 'Carrot' ],
    [ 2, 'Cucumber' ],
    [ 3, 'Cabbage' ],
    [ 4, 'Tomato' ],
    [ 5, 'Onion' ],
    [ 6, 'Wheat' ],
    [ 7, 'Celery' ],
    [ 8, 'Cauliflower' ],
    [ 9, 'Broccoli' ],
    [ 10, 'Pea' ],
    [ 11, 'Turnip' ],
    [ 12, 'Potato' ],
    [ 13, 'Corn' ],
    [ 14, 'Bell pepper' ],
    [ 15, 'Radish' ],
    [ 16, 'Lettuce' ],
    [ 17, 'Spinach' ],
    [ 18, 'Asparagus' ],
    [ 19, 'Oregano' ],
    [ 20, 'Mushroom' ],
    [ 21, 'Bean' ],
    [ 22, 'Garlic' ],
    [ 23, 'Basil' ],
    [ 24, 'Beet' ],
    [ 25, 'Lentils' ],
    [ 26, 'Barley' ],
    [ 27, 'Rye' ],
    [ 28, 'Parsley' ],
    [ 29, 'Eggplant' ],
    [ 30, 'Arugula' ],
    [ 31, 'Sweet potato' ],
    [ 32, 'Brussels sprouts' ],
    [ 33, 'Cilantro' ],
    [ 34, 'Hot pepper' ],
    [ 35, 'Fennel' ],
    [ 36, 'Ginger' ],
    [ 37, 'Rosemary' ],
    [ 38, 'Squash' ],
    [ 39, 'Leek' ],
    [ 40, 'Parsnip' ],
    [ 41, 'Artichoke' ],
    [ 42, 'Oat' ],
    [ 43, 'Pumpkin' ],
    [ 44, 'Rutabaga' ],
    [ 45, 'Thyme' ],
    [ 46, 'Kale' ],
    [ 47, 'Tomatillo' ],
    [ 48, 'Zucchini' ],
    [ 49, 'Dill' ],
    [ 50, 'Soy bean' ],
    [ 51, 'Scallion' ],
    [ 52, 'Rhubarb' ],
    [ 53, 'Endive' ],
    [ 54, 'Anise' ],
    [ 55, 'Horseradish' ],
    [ 56, 'Okra' ],
    [ 57, 'Marjoram' ],
    [ 58, 'Jicama' ],
    [ 59, 'Millet' ],
    [ 60, 'Kohlrabi' ],
    [ 61, 'Sage' ],
].map(item => ({
    id: item[0],
    name: item[1]
}));

export { ITEMS };